name: CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/future-re/ubuntu22.04-clang20-boost1.89-gtest1.17

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache ccache
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('**/CMakeLists.txt','**/*.cpp','**/*.c','**/*.h','**/*.hpp') }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Show tool versions
        run: |
          uname -a
          cmake --version || true
          clang++ --version || true

      - name: Configure project
        env:
          CCACHE_DIR: /home/runner/.ccache
        run: cmake -B build -DCMAKE_CXX_STANDARD=23

      - name: Build project
        run: cmake --build build -j$(nproc)

      - name: Run tests
        run: ctest --test-dir build --output-on-failure