name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache ccache
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('**/CMakeLists.txt','**/*.cpp','**/*.c','**/*.h','**/*.hpp') }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Show tool versions
        run: |
          uname -a
          lsb_release -a || true
          cmake --version || true
          clang --version || true

      - name: Install basic deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake pkg-config wget ccache git python3

      # 可选：保留安装 clang-20（如需）
      - name: Install Clang 20
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20 || true
          sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang-20 100 || true
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-20 100 || true
          sudo update-alternatives --set cc /usr/bin/clang-20 || true
          sudo update-alternatives --set c++ /usr/bin/clang++-20 || true

      # 缓存 vcpkg 的下载/installed 等目录以减少重复构建
      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: |
            vcpkg/installed
            vcpkg/packages
            vcpkg/downloads
          key: ${{ runner.os }}-vcpkg-1.89-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      - name: Install vcpkg and Boost 1.89
        run: |
          git clone --depth=1 https://github.com/microsoft/vcpkg.git vcpkg
          ./vcpkg/bootstrap-vcpkg.sh
          # 安装需要的 Boost 组件（会构建一次，后续由 cache 加速）
          ./vcpkg/vcpkg install boost-filesystem boost-regex boost-process --triplet x64-linux

      # 如果 libgtest-dev 仍需构建静态库（保持原先逻辑）
      - name: Build and install GoogleTest
        run: |
          sudo apt-get install -y libgtest-dev cmake || true
          tmpdir=$(mktemp -d)
          pushd "$tmpdir"
          cmake /usr/src/gtest -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release -j$(nproc)
          sudo cp *.a /usr/lib || true
          popd
          rm -rf "$tmpdir"

      # 配置项目，使用 vcpkg toolchain
      - name: Configure project
        env:
          CCACHE_DIR: $HOME/.ccache
        run: |
          cmake -B build \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_CXX_STANDARD=23 \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build project
        run: cmake --build build -j$(nproc)

      - name: Run tests
        run: ctest --test-dir build --output-on-failure